# Generated by Django 3.0.3 on 2020-02-20 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Кузовы',
            },
        ),
        migrations.CreateModel(
            name='BrandCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Список автомобильных марок',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Объем двигателя',
                'verbose_name_plural': 'Список объемов двигателя',
            },
        ),
        migrations.CreateModel(
            name='ModelCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('brandCar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avto.BrandCar', verbose_name='Тип авто')),
            ],
            options={
                'verbose_name': 'Тип модели',
                'verbose_name_plural': 'список моделей',
            },
        ),
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avto.Body', verbose_name='Тип кузова')),
                ('brandCar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avto.BrandCar', verbose_name='Тип авто')),
                ('modelCar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avto.ModelCar', verbose_name='Тип модели')),
                ('volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avto.Volume', verbose_name='Объем двигателя')),
            ],
            options={
                'verbose_name': 'Тип авто',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
