# Generated by Django 3.0.3 on 2020-02-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='avto.Categories')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField()),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='количество в наличии')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.PositiveSmallIntegerField(default=0)),
                ('avto', models.ManyToManyField(to='avto.Avto')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avto.Categories', verbose_name='категория товара')),
            ],
            options={
                'verbose_name': 'Автозапчасти',
                'verbose_name_plural': 'Список запчастей',
            },
        ),
    ]
