# Generated by Django 3.0.3 on 2020-02-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0002_categories_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='avto.Categories'),
        ),
    ]
